### ISSUE TITLE
Not recognizing sub construction as a sentence

### ISSUE THREAD

**Issue by vduong143** [genelkim/ulf-sanity-checker#44] opened 2019-11-15 20:41 UTC
************************************
## Sanity checking formula (before preprocessing).
```
((SUB DOWN.ADV-A ((THE.D CEILING.N) ((PAST COME.V) *H))) AND.CC
 ((THE.D DOG.N) ((PAST GO.V) AWAY.ADV-A)))
```

## Sanity checking formula (after preprocessing).
```
(((SUB DOWN.ADV-A ((THE.D CEILING.N) ((PAST COME.V) *H))) AND.CC
  ((THE.D DOG.N) ((PAST GO.V) AWAY.ADV-A)))
 NIL NIL)
```

## Possible errors

Possibly failed conditions:
  _"UNKNOWN detected in type analysis.  Please ensure this isn't from an annotation error."_
Ann segment:
  ```
NIL
```
Predicted constituent types ((list of types) -- constituent)

## Formula with predicted types (for debugging).

```
(((TYPES UNKNOWN)
  (((TYPES UNKNOWN)
    (SUB DOWN.ADV-A
         ((TYPES TENSED-SENT)
          (((TYPES TERM) (THE.D CEILING.N))
           ((TYPES PRED TENSED-VERB)
            (((TYPES PRED TENSED-VERB) (PAST COME.V)) *H))))))
   AND.CC
   ((TYPES TENSED-SENT)
    (((TYPES TERM) (THE.D DOG.N))
     ((TYPES PRED TENSED-VERB)
      (((TYPES PRED TENSED-VERB) (PAST GO.V)) AWAY.ADV-A)))))))
```

NIL

####################################

**Comment by genelkim** [comment] 2020-05-05 01:34
This case added in https://github.com/genelkim/ulf-sanity-checker/pull/63. Duplicate of https://github.com/genelkim/ulf-sanity-checker/issues/37

**Closed by genelkim** 2020-05-05 01:34 UTC
